image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
secrets:
- aed04503-7a99-4335-810c-e5d0249d9fbb # ssh key
packages:
- hut
environment:
  site: muffin.ink
tasks:
- package: |
    cd $site
    tar -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz
    hut pages publish -d www.$site site.tar.gz
