base_url = "https://muffin.ink"
compile_sass = false
build_search_index = false
generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "OneHalfLight", filename = "generated-themes/syntax-theme-light.css" },
  { theme = "one-dark", filename = "generated-themes/syntax-theme-dark.css" },
]

[extra]
