name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [master]

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Download zola
      run: |
        curl -o zola.tar.gz -L https://github.com/getzola/zola/releases/download/v0.20.0/zola-v0.20.0-x86_64-unknown-linux-gnu.tar.gz
        echo "ca7ed5b33a739c5b5b35a0e207e5c3578a652cd12b61c675763b3ff34c322d08 zola.tar.gz" > zola-sha256
        sha256sum -c zola-sha256
        tar -xzf zola.tar.gz
    - name: Build website
      run: ./zola build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  upload-to-branch:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup repository
      run: |
        git config --global user.email "actions-user@users.noreply.github.com"
        git config --global user.name "actions-user"
        git init
        git remote add origin "https://actions-user:$GH_TOKEN@github.com/GarboMuffin/muffin.ink.git"
        git checkout -B gh-pages
      env:
        GH_TOKEN: "${{ github.token }}"
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: github-pages
    - name: Extract
      run: |
        tar -xf artifact.tar
        rm artifact.tar
    - name: Commit
      run: |
        git stage .
        git commit -m "Upload built website"
    - name: Push
      run: git push --force --set-upstream origin gh-pages
